{{- if .Values.minecraftServer.monitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: mine-release
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: mc-monitor
        static_configs:
          - targets:
              - mc-monitor:8080
{{ end }}
---
{{- if .Values.minecraftServer.monitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mine-release
data:
  grafana.ini: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
{{ end }}